name: Press Tests

on: push

env:
  DB_NAME: test_frappe
  DB_USER: test_frappe
  DB_PASSWORD: test_frappe

jobs:
  format:
      name: 'Black and Flake8'
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install frappe-bench flake8 git+https://github.com/adityahase/black
      - name: Black Test
        run: |
          black --check ${GITHUB_WORKSPACE}/press/press

      - name: Flake8 Test
        run: |
          flake8 --ignore W191,E501,W503 ${GITHUB_WORKSPACE}/press/press
          
  build:
    runs-on: ubuntu-22.04
    env:
      USER: ${{ github.actor }}
    strategy:
      fail-fast: false
      matrix:
       db: ["mariadb"]
       container: [1, 2]
       
    services:
      mariadb:
        image: mariadb:10.6
        env:
          MARIADB_ROOT_PASSWORD: travis
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 14.x
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y mariadb-client redis-server

    - name: Initialize Frappe Bench
      run: |
        cd ..
        bench init frappe-bench --skip-assets --python $(which python)
        cd frappe-bench
        bench get-app ../press press
        bench setup requirements --dev
        mkdir sites/test_site
        cp apps/press/.travis/mariadb.json sites/test_site/site_config.json
        mysql -u root -e "SET GLOBAL character_set_server = 'utf8mb4'"
        mysql -u root -e "SET GLOBAL collation_server = 'utf8mb4_unicode_ci'"
        mysql -u root -e "DROP DATABASE IF EXISTS $DB_NAME"
        mysql -u root -e "CREATE DATABASE $DB_NAME"
        mysql -u root -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD'"
        mysql -u root -e "GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost'"
        mysql -u root -e "UPDATE mysql.user SET Password=PASSWORD('travis') WHERE User='root'"
        mysql -u root -e "FLUSH PRIVILEGES"
        sed -i 's/watch:/# watch:/g' Procfile
        sed -i 's/schedule:/# schedule:/g' Procfile
        sed -i 's/socketio:/# socketio:/g' Procfile
        sed -i 's/redis_socketio:/# redis_socketio:/g' Procfile
        bench start &
        bench --site test_site reinstall --yes
    - name: Backbone Base Image Build
      if: contains(github.event.head_commit.message, 'travis:rebuild-image')
      run: |
        sudo rm /usr/local/bin/packer
        python3 /path/to/backbone/setup.py
        sudo -E su $USER -c '~/virtualenv/python3.7/bin/backbone hypervisor build'
        sudo -E su $USER -c '~/virtualenv/python3.7/bin/backbone hypervisor up'
        sudo -E su $USER -c '~/virtualenv/python3.7/bin/backbone hypervisor ssh -c "echo Hello, World"'
      env:
        USER: $USER
    - name: Press Tests
      run: |
        bench --site test_site run-tests --app press
        cd apps/press/dashboard && yarn run test
